# Generated by Django 4.1.3 on 2022-11-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('kp_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[(1, 'Фильм'), (2, 'Сериал')], max_length=1)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('imbd_id', models.CharField(blank=True, max_length=128, null=True)),
                ('poster_url', models.SlugField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, max_length=128, null=True)),
                ('kp_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
