# Generated by Django 4.1.3 on 2023-01-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imbd_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movieLength',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='preview_url',
            field=models.SlugField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[(1, 'Фильм'), (2, 'Сериал'), (3, 'Мультик'), (4, 'Аниме'), (5, 'Мульт-сериал'), (6, 'ТВ-шоу')], max_length=1),
        ),
    ]
