# Generated by Django 4.1.3 on 2023-01-27 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movie_alternative_name_movie_imbd_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movieLength',
            new_name='movie_length',
        ),
    ]
