# Generated by Django 4.1.3 on 2023-01-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_movielength_movie_movie_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imbd_rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='kp_rating',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
