# Generated by Django 4.1.3 on 2023-01-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_movie_imbd_rating_movie_imdb_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imbd_id',
            new_name='imdb_id',
        ),
    ]
