# Generated by Django 4.1.3 on 2023-01-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_imbd_id_movie_imdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
    ]
