# Generated by Django 4.1.6 on 2023-02-09 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_mfuser_friends_alter_friendship_receiver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
