# Generated by Django 4.1.6 on 2023-03-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfuser',
            name='bookmarks',
            field=models.ManyToManyField(to='core.movie'),
        ),
    ]
