# Generated by Django 4.1.6 on 2023-03-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mfuser_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfuser',
            name='public_bookmarks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mfuser',
            name='public_reviews',
            field=models.BooleanField(default=False),
        ),
    ]
