# Generated by Django 4.1.6 on 2023-03-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mfuser_public_bookmarks_mfuser_public_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfuser',
            name='only_friends_reviews',
            field=models.BooleanField(default=False),
        ),
    ]
