# Generated by Django 4.1.6 on 2023-03-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_bookmark_mfuser_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=1024),
        ),
    ]
